### ISSUE TITLE
24-hour clock format over 12-hour clock format

### ISSUE THREAD

**Issue by PatrickPedersen** [THE-BWC/OpServ-Issues#10]
There seems to be a lot of room for error in OpServ regarding times. One thing I think that could be improved to reduce issues is to remove the 12 hour formatting and utilize the 24 hour clock. This is an international and military standard, and as we are both veteran founded and international, utilizing the 24 hour clock seems appropriate.

As it currently stands, the clock will actually let you put in fictional numbers like 13:00 AM, and this data entry error will still allow you to submit the Op but create a "Unknown time" error. Upon editing the op again, the time automatically corrects, so it's clear it knew what I meant but the clock seems to be set up to utilize both the 12 and 24 hour format currently. We need to pick one and stick with it, and for the above mentioned reasons, I think we should utilize the 24 hour clock.

**Comment by PatrickPedersen** [comment]
I should probably mention that if we drop 12-hour clock support and go all in on 24-hour clock, we can get #7 and #11 done in the same batch.
@Goltred

**Comment by Goltred** [comment]
I definitely agree. I have finished setting up the dev environment on my end but i was running into a small issue that i haven't had the time to fix. I know where the changes need to go but I don't want to blindly make changes without the chance of proper testing.
I'll definitely get this done though :)

**Comment by PatrickPedersen** [comment]
Changes and fixes have been deployed
