### ISSUE TITLE
Show the name of the day an operation is starting

### ISSUE THREAD

**Issue by PatrickPedersen** [THE-BWC/OpServ-Issues#11]
Show the name of the day an operation is starting. 
E.g. Saturday 2020-06-20 23:00 instead of 2020-06-20 23:00

**Comment by Goltred** [comment]
@PatrickPedersen Where do you want this displayed like that? I assume it is when displaying ops? Like here? 
![image](https://github.com/THE-BWC/OpServ-Issues/assets/5765834/aa1e875c-b177-45c9-a963-353b4eeefacc)

And here ?
![image](https://github.com/THE-BWC/OpServ-Issues/assets/5765834/123f0f69-6266-4a53-b6b1-9ec0ed9739db)

Basically anywhere where the date is a label and is not an input field? (e.g. also in past ops?)

**Comment by PatrickPedersen** [comment]
We would probably want it anywhere that ops is being mentioned, yes.
So on the home page, the Jacket, Ops attended, Ops led, Ops Attention, etc.

**Comment by PatrickPedersen** [comment]
Pushed live
