### ISSUE TITLE
Add search functionality to AAR list

### ISSUE THREAD

**Issue by PatrickPedersen** [THE-BWC/OpServ-Issues#15]
Can we have a search field for our members list? With the current format on creating our AARs, having the ability to search for somebody would be very useful as we use an unalphabetized list from discord to determine who attended our ops.

**Comment by Goltred** [comment]
Is this for this section?
![image](https://github.com/THE-BWC/OpServ-Issues/assets/5765834/faea3823-0f9c-4fc6-82c0-bdae6ae0b107)

Optionally, we could also track a new discord bot feature where we can read interactions to messages (possibly, messages in specific attendance channels perhaps). This would allow us to get the interaction, get the message, from the message get the operation id, and then add the member to the attendance of that operation through some sql/opserv api calls

**Comment by PatrickPedersen** [comment]
>Is this for this section?

Yes, that the section.

>Optionally, we could also track a new discord bot feature where we can read interactions to messages (possibly, messages in specific attendance channels perhaps). This would allow us to get the interaction, get the message, from the message get the operation id, and then add the member to the attendance of that operation through some sql/opserv api calls

Hmm... That may be complicating it quite a bit. I don't recall who mentioned it, but we could also just post the attendance link in the AAR channel. Of course, the Op Lead is still responsible for ensuring attendance is correct and that no one who shouldn't be there is.

**Comment by PatrickPedersen** [comment]
Deployed
