### ISSUE TITLE
Opserv page that displays who is certified to teach a specific training

### ISSUE THREAD

**Issue by PatrickPedersen** [THE-BWC/OpServ-Issues#18]
Please consider making the information of who is *certified to teach* a certain training visible in some way on opserv, either to everyone through a dropdown on the training or similar, or to C&S through an opserv report similar to the award check report or custom roster showing who has passed a certain training.

Currently you need to make educated guesses and check people's jackets one by one to compile this information, or track certifications in parallel through forum threads, google docs etc.

**Comment by Goltred** [comment]
I was playing a bit with this today... and i think we could add this information in the overall information of the training itself?

Like this:
![image](https://github.com/THE-BWC/OpServ-Issues/assets/5765834/fd8c8cf4-fda1-49be-886e-481800bee077)

thoughts?

**Comment by PatrickPedersen** [comment]
Showing it inside the training sounds ideal.

If Command teams would like a report showing a list of their trainings and the certified members, we could always make that. But showing it inside the trainings sounds like a good starting point.

**Comment by PatrickPedersen** [comment]
Just gonna post this image here as well:
![Image](https://github.com/THE-BWC/OpServ-Issues/assets/44923215/ec6238dd-9c69-42ee-9007-e29256473181)

**Comment by PatrickPedersen** [comment]
Pushed live
