### ISSUE TITLE
When returning member from LOA, comment isn't being generated.

### ISSUE THREAD

**Issue by PatrickPedersen** [THE-BWC/OpServ-Issues#22]
Error:
![image](https://github.com/THE-BWC/OpServ-Issues/assets/44923215/35f0d050-236b-4474-aadb-adc26e37519d)

**Comment by Goltred** [comment]
Hmmm... well, do we want to add a default comment here? Error is pretty self-explanatory, but i 'm not sure how the LOA system works to know if there's a message we should be grabbing from somewhere to pass to this function.
A quick fix is to call this addComment() with `Member has returned from LOA`.

**Comment by PatrickPedersen** [comment]
Yeah, I didn't know that it errored out like that until I went to use it on Shims. I assume it's just missing the actual text to insert. Your quick fix is essentially what I would do to fix it.

**Comment by PatrickPedersen** [comment]
Deployed
