### ISSUE TITLE
404 when clicking on members button

### ISSUE THREAD

**Issue by Goltred** [THE-BWC/OpServ-Issues#23]
Clicking the "members" button in the opserv main menu is throwing a 404 message:
![image](https://github.com/THE-BWC/OpServ-Issues/assets/5765834/ac4e95de-6a73-489d-9beb-dab8fbbde55c)

The link on that button leads to: https://the-bwc.com/forum/members
The similar option inside the forum leads to: https://the-bwc.com/forum/index.php?members/

**Comment by PatrickPedersen** [comment]
I believe that link is in the includes/header.php file. We just need to update it. Easy enough.

**Comment by PatrickPedersen** [comment]
Deployed
