### ISSUE TITLE
Broken "Streamer SOP" link in PAO: Basic Streamer Qual training

### ISSUE THREAD

**Issue by Goltred** [THE-BWC/OpServ-Issues#25]
The link for "Streamer SOP" displayed in the "[PAO: Basic Streamer Qual](https://the-bwc.com/opserv/training.php?id=171&info)" leads to a 404 error.

The current link is: http://the-bwc.com/forum/showthread.php?72920-STREAMING-SOP

Looking at the forums, the following seems to be the Content Creators ASOP, but i am not sure if this is the right one to be used: https://the-bwc.com/forum/index.php?threads/s-9-content-creators-asop.2906/

**Comment by PatrickPedersen** [comment]
That would be up to @THE-BWC/s-9 to deal with. That's not up to us; it is just an easy training update request from their end.

**Comment by Goltred** [comment]
ah, you are right... i didn't even process where "exactly" this was supposed to go :D
sry for the noise!

**Comment by PatrickPedersen** [comment]
It's all good :)
