### ISSUE TITLE
Redacted is shown for own led ops

### ISSUE THREAD

**Issue by Goltred** [THE-BWC/OpServ-Issues#26]
When looking at led ops in the jacket, the REDACTED string can be seen for those where thr user apparently has no opsec access.

This was reported by aniron in [discord](https://discord.com/channels/378419940027269130/913449794201075712/1218893547286302781)

A decision needs to be made for this situation.
Do we keep it as it currently is?
Do we remove opsec check in this part because the user led these ops?
Do we only show the game name so they can know which game are talking about?

**Comment by jarnehed** [comment]
Also I am not sure what opsec-enabled op I could have led where I would not have opsec clearance. I have only led Star Citizen operations in the last few years, so this might be a bug in addition to a feature request.

/aniron

**Comment by PatrickPedersen** [comment]
Okay, that doesn't make sense. The op in question is this:
[[DRAGON] Strike DRAGMAN Development I (invite only)](https://the-bwc.com/opserv/operation.php?id=40499)

You have OPSEC access. Checked the DB to be sure. I also checked the code that changes the data. Everything should work as intended. So, I don't understand why it would show up as Redacted.

**Comment by PatrickPedersen** [comment]
>A decision needs to be made for this situation.
Do we keep it as it currently is?
Do we remove opsec check in this part because the user led these ops?
Do we only show the game name so they can know which game are talking about?

The only thing I would be willing to allow currently is the game name. Anything else would require a much broader discussion with BWC.

**Comment by jarnehed** [comment]
Interestingly I can see that OP without redactions on my "ops attended" tab, I can open and view it as normal using your link.

It appears the issue affects others as well, Fluff reported several redacted items on her ops led tab.

**Comment by PatrickPedersen** [comment]
Well, if it's specific to the op-lead menu, that helps greatly with troubleshooting.
I'll take a look at it.

**Comment by PatrickPedersen** [comment]
@jarnehed Pushed a possible fix. Could you please check and see if it works now?

**Comment by jarnehed** [comment]
> @jarnehed Pushed a possible fix. Could you please check and see if it works now?

Appears to have done the trick! I no longer see redacted entries in either my own ops led tab or in Fluff's.

Thanks!

**Comment by PatrickPedersen** [comment]
Perfect!
