### ISSUE TITLE
Display training's certified trainer function does not work when no description is set

### ISSUE THREAD

**Issue by von-Benette** [THE-BWC/OpServ-Issues#27]
Steps to reproduce:
Go to personal jacket
Go to trainings
Click on training description link
IF training has no description saved ->"[Missing Details] Could not find any material"
![Screenshot - 18 03 2024 , 00_10_36](https://github.com/THE-BWC/OpServ-Issues/assets/26607388/65cd5762-8b9b-4c9a-8781-18ea79bd55d0)

**Comment by PatrickPedersen** [comment]
Thanks for the report. We'll look into getting it fixed :)

**Comment by Goltred** [comment]
Is this... normal? Does it make sense to have a training with no base information yet have trainers assigned? The fix is simple (PR incoming) but I just wonder if there should be some validation happening elsewhere since the conditions to show this error was `has description AND has syllabus`

**Comment by PatrickPedersen** [comment]
Normal? No, but it does happen.
I'll look over the PR once I am done with work.

**Comment by PatrickPedersen** [comment]
Fix has been deployed
