### ISSUE TITLE
Should we have a dedicated "operation" page to display past operation data?

### ISSUE THREAD

**Issue by Goltred** [THE-BWC/OpServ-Issues#28]
Currently, the only way of looking at a past operation AAR (as a user) is to go to Past Ops, looking for the operation and clicking actions in the bottom of the box.
![image](https://github.com/THE-BWC/OpServ-Issues/assets/5765834/1244d635-24eb-4728-ae26-fe53bef3cde5)

This prevents us from actually linking to a specific operation for reference... So should we have a new page for showing operation data in a friendly manner?

A page like this (e.g. operationInfo.php?op=123), would then be able to show in a single page the following information without having to click on different links:
Operation Details
Description
AAR
Attendees

This would allow us to provide a link to a particular operation, potentially reducing the need for posting the FULL AAR in the forums to get feedback on a given op.

**Comment by PatrickPedersen** [comment]
Do you mean this page? https://the-bwc.com/opserv/operation.php?id=31086
I am all for making it more easy to get to.

**Comment by Goltred** [comment]
Yes, So my confusion came from the fact that you can only access this page when looking at the operation list through the "Ops Led" or "Ops Attended" menus inside the jacket, but not the "Past Ops" option in the top menu of opserv. I'll just add a link there to be able to go to the operation as well.

**Comment by Goltred** [comment]
Another question... is there a specific reason why we don't want to show formatting for description and AAR? It feels to me that sometimes there's important data in descriptions that are harder to see because the html tags are being removed from it.

**Comment by PatrickPedersen** [comment]
That seems like a CSS issue. Formatting should be shown in the description and AAR

Also the HTML tags are still there. Hence why I think it's CSS specific

**Comment by Goltred** [comment]
Yep it is... it comes down to a bunch of different rules in the opserv_main that is causing certain elements to lose their styling... e.g ol and ul tags are losing their bullet point styles.

I was just unsure if this is what we want or if this is something we might want to improve. Since op descriptions and AAR are inside their own classed containers, i feel that we could introduce a new set of rules in the form of `.operation-description > *` that should only affect the elements inside the operation boxes... allowing us to show the formatting that the person is giving to their descriptions and AARs instead of just showing plain text

This is after a few changes
![image](https://github.com/THE-BWC/OpServ-Issues/assets/5765834/f4587128-aa5e-466f-a86f-b0e0b6557e21)

Should I continue doing something about it or just leave it as is for now?

**Comment by PatrickPedersen** [comment]
Sorry for the long break.

Yes, please. If you still have time and want to do it.
The approach is fine with me. It helps to contain the specific styling to those containers only.

**Comment by Goltred** [comment]
I think this has been handled by this one: https://github.com/THE-BWC/OpServ-V9/pull/27 :)

**Comment by PatrickPedersen** [comment]
In that case. I'll close this one :)
