### ISSUE TITLE
[BUG] - SC RASP training student material not displayed when clicked on from opserv 'home'

### ISSUE THREAD

**Issue by von-Benette** [THE-BWC/OpServ-Issues#31]
### Description

![Screenshot - 20 05 2024 , 21_44_37](https://github.com/THE-BWC/OpServ-Issues/assets/26607388/53c8c490-f403-43a5-91af-0a7cf3dd7ddf)
![Screenshot - 20 05 2024 , 21_45_09](https://github.com/THE-BWC/OpServ-Issues/assets/26607388/6c60392e-6ac4-4ce7-94df-734ffd4d33f8)

Steps
1 - Open opserv.
2 - Be in SC
3 - drop-down upcoming SC ops
4 - click on Ranger Assessment and Selection Process's student material
5 - nothing happens, student material doesn't open

Expected Behaviour
5 - Student material is displayed 

As shown in second screenshot, the training DOES have student material, and it is successfully displayed when accessed from the trainings section under our jackets.

Reproduced by:
von_Benette
Fluffulupigas
aniron

NOT Reproduced by:
Nightstalker (creator of the training)

### Browsers

Firefox, Chrome

### OS

Windows

**Comment by jarnehed** [comment]
Looking closer at the link reveals this, which might help. /aniron

![Screenshot_20240520-212045_Chrome.jpg](https://github.com/THE-BWC/OpServ-Issues/assets/24810721/44115db1-a8bb-467f-809b-efa3102e755f)

**Comment by PatrickPedersen** [comment]
This has been fixed.
