### ISSUE TITLE
[BUG] - AAR attendance/squad UI overlaps itself on Android.

### ISSUE THREAD

**Issue by jarnehed** [THE-BWC/OpServ-Issues#34]
### Description
Submitter: aniron

Squads overlaps the list of potential attendees on Android/Chrome.
Buttons for "add squad" and "submit AAR" overlaps page title.
See attached screenshots.
Problem exists both in portrait and landscape mode.

![Screenshot_20240918-090132_Chrome](https://github.com/user-attachments/assets/203de34f-79d4-4542-8bb1-abf5383d7438)
![Screenshot_20240918-090151_Chrome](https://github.com/user-attachments/assets/4849a226-7908-41d6-9e83-b6d1e06b9877)

### Browsers

Chrome

**Comment by PatrickPedersen** [comment]
Never seen that before, I'll look into that

**Comment by PatrickPedersen** [comment]
This has been fixed and deployed along with some other mobile-friendly CSS changes.
