### ISSUE TITLE
[BUG] - Pre-Op Squad Assignments breaks up Squads in Home Page Op UI

### ISSUE THREAD

**Issue by Q2M-x** [THE-BWC/OpServ-Issues#39]
### Description

![Image](https://github.com/user-attachments/assets/d6fec9a7-bbfb-4d79-888d-eb8f44cbfb5a)
![Image](https://github.com/user-attachments/assets/0e94b4a8-ee7d-4f71-9096-bd756140ea16)
![Image](https://github.com/user-attachments/assets/076b2a92-5b6e-4831-be1b-1fbf63b66273)

Image 1 is before assigning squads
Image 2 is after assigning squads
Image 3 is the squads on the home page op UI with squads split in a seemingly random manner

### Browsers

Firefox

### OS

Windows

**Comment by PatrickPedersen** [comment]
Well, that is certainly interesting... I'll put it on my list for tomorrow.

**Comment by PatrickPedersen** [comment]
That was a more straightforward fix than I thought. This has been fixed.
