### ISSUE TITLE
Proper date checking on operation creation

### ISSUE THREAD

**Issue by PatrickPedersen** [THE-BWC/OpServ-Issues#7]
Incorrectly setting the Date Start and/or Date End on operation creation. Will default to undefined/null and will throw the operation back to the start of Epoch: January 1, 1970.

UI should prevent the form from being submitted until an actual date has been inserted, instead of defaulting to the start of Epoch.

**Comment by PatrickPedersen** [comment]
#10

**Comment by Goltred** [comment]
@PatrickPedersen I can help out with this one if you want

**Comment by PatrickPedersen** [comment]
@Goltred You are welcome to take a shot a it :)

**Comment by Goltred** [comment]
This should be fixed with https://github.com/THE-BWC/OpServ-V9/pull/11

**Comment by PatrickPedersen** [comment]
Changes and fixes deployed
